# Site settings
title: "CS373 Spring 2015: Taylor Barnett"
email: "taylormbarnett [at] utexas [dot] edu"
description: > # this means to ignore newlines until "baseurl:"
  "An extra credit blog for CS373 at The University of Texas at Austin"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tbarn.github.io" # the base hostname & protocol for your site
twitter_username: "taylor_atx"
github_username:  "tbarn"

# Build settings
markdown: kramdown
